#include <iostream>
#include <iomanip>
#include <math.h>
#include <algorithm>
#include <vector>
#include <set>
#include <string>
#include <iterator>
#include <cmath>
#include <fstream>
#include <sstream>